FROM ubuntu:24.04

RUN apt-get update && apt-get install -y \
    adduser sudo unzip wget curl file

# Create a new user and add to the sudo group
RUN adduser --disabled-password --gecos "" builder && \
    echo "builder:builder" | chpasswd && \
    adduser builder sudo && \
    echo "builder ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

# Customize the bash prompt
RUN echo "PROMPT_DIRTRIM=2" >> /home/builder/.bashrc && \
	echo "PS1='\[\e[0;32m\]\u\[\e[0m\]@\[\e[0;34m\]docker(\h)\[\e[0m\]:\w\$ '" >> /home/builder/.bashrc

# Install dependencies
RUN apt-get update && apt-get install -y \
    build-essential cmake g++ git \
    qt6-base-dev \
    qt6-declarative-dev \
    qml6-module-qt-labs-qmlmodels \
    qml6-module-qtqml-workerscript \
    qml6-module-qtquick \
    qml6-module-qtquick-templates \
    qml6-module-qtquick-layouts \
    qml6-module-qtquick-window \
    qt6-tools-dev-tools \
    qt6-svg-dev qt6-tools-dev \
    libxkbcommon-dev ninja-build

# AppImage stuff
RUN wget https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage \
        -O /opt/linuxdeploy.AppImage && chmod +x /opt/linuxdeploy.AppImage ; \
    wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage \
        -O /opt/appimagetool.AppImage && chmod +x /opt/appimagetool.AppImage

USER builder
WORKDIR /workdir

CMD ["/bin/bash"]
