#!/bin/bash
# Apply all libiec61850 patches. Safe to call multiple times — skips already-applied patches.
# Patches must be generated by `git diff` to ensure correct context lines.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" && pwd)"
REPO_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
SUBMODULE_DIR="$REPO_DIR/3rdparty/libiec61850"

if [ ! -d "$SUBMODULE_DIR/.git" ] && [ ! -f "$SUBMODULE_DIR/.git" ]; then
    echo "Warning: libiec61850 submodule not initialized, skipping patches."
    exit 0
fi

cd "$SUBMODULE_DIR"

echo "==> Submodule: $(pwd)"
echo "    autocrlf=$(git config core.autocrlf 2>/dev/null || echo unset)"
echo "    dirty files: $(git status --short 2>/dev/null | wc -l)"

applied=0
failed=0
for patch in "$REPO_DIR"/3rdparty/libiec61850-*.patch; do
    [ -f "$patch" ] || continue
    name="$(basename "$patch")"

    # Try applying
    if git apply --check "$patch" 2>/dev/null; then
        echo "==> Applying $name..."
        git apply "$patch"
        applied=$((applied + 1))
        continue
    fi

    # Check if already applied
    if git apply --check --reverse "$patch" 2>/dev/null; then
        echo "==> Skipping $name (already applied)"
        continue
    fi

    # Failed — show why
    echo "==> ERROR: $name failed to apply!"
    echo "    git apply --check output:"
    git apply --check "$patch" 2>&1 | sed 's/^/    /' || true

    # Try with --ignore-whitespace as fallback
    if git apply --ignore-whitespace --check "$patch" 2>/dev/null; then
        echo "    Retrying with --ignore-whitespace..."
        git apply --ignore-whitespace "$patch"
        applied=$((applied + 1))
    else
        echo "    --ignore-whitespace also fails. Patch cannot be applied."
        failed=$((failed + 1))
    fi
done

echo "==> Applied: $applied, Failed: $failed"

if [ $failed -gt 0 ]; then
    exit 1
fi
