FROM ubuntu:24.04

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential cmake g++ git ninja-build \
    file patchelf fakeroot dpkg-dev \
    qt6-base-dev \
    qt6-declarative-dev \
    qml6-module-qt-labs-qmlmodels \
    qml6-module-qtqml-workerscript \
    qml6-module-qtquick \
    qml6-module-qtquick-controls \
    qml6-module-qtquick-dialogs \
    qml6-module-qtquick-templates \
    qml6-module-qtquick-layouts \
    qml6-module-qtquick-window \
    qt6-tools-dev-tools \
    qt6-svg-dev qt6-tools-dev \
    libxkbcommon-dev \
    && rm -rf /var/lib/apt/lists/*

# Allow git to work on mounted volumes owned by any user
RUN git config --system safe.directory '*'

WORKDIR /workdir

CMD ["/bin/bash"]
