FROM ubuntu:24.04

# Install dependencies
RUN apt-get update && \
    apt-get install -y \
    sudo \
    cmake g++ \
    qt6-base-dev qt6-declarative-dev

# Rename the existing ubuntu user to builder
RUN usermod -l builder -d /home/builder -m ubuntu && \
    groupmod -n builder ubuntu && \
    echo "builder:builder" | chpasswd && \
    usermod -aG sudo builder && \
    echo "builder ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

# Copy the application source code
#COPY ../ /IEDClient
#WORKDIR /IEDClient
# Build and run tests
#RUN mkdir -p builder && cd builder && \
#    cmake .. && \
#    make && \
#    ctest

USER builder
WORKDIR /

CMD ["/bin/bash"]